// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Cartas.BD.Datos;

#nullable disable

namespace Proyecto_Cartas.BD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251006182441_test1")]
    partial class test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Amigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Usuario1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Usuario2Id")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId1")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Usuario1Id");

                    b.HasIndex("Usuario2Id");

                    b.ToTable("Amigos");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int>("cantidadMonedas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Billeteras");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ataque")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("NivelCarta")
                        .HasColumnType("int");

                    b.Property<string>("NombreCarta")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TipoCarta")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Velocidad")
                        .HasColumnType("int");

                    b.Property<int>("Vida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cartas");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.CartaApertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadCartasObtenidas")
                        .HasColumnType("int");

                    b.Property<int>("CartaSobreID")
                        .HasColumnType("int");

                    b.Property<int>("CompraSobreID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaSobreID");

                    b.HasIndex("CompraSobreID");

                    b.ToTable("CartasApertura");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.CartaSobre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("ProbabilidadCartaSobre")
                        .HasColumnType("int");

                    b.Property<int>("SobreID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaID");

                    b.HasIndex("SobreID");

                    b.ToTable("CartasSobre");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.CompraSobre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("SobreID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SobreID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("ComprasSobre");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.ConfiguracionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int>("VolumenMusica")
                        .HasColumnType("int");

                    b.Property<int>("VolumenSFX")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.ToTable("ConfiguracionesUsuario");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.EstadoCarta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ataque")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("InventarioID")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioPartidaID")
                        .HasColumnType("int");

                    b.Property<int>("Velocidad")
                        .HasColumnType("int");

                    b.Property<int>("Vida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventarioID");

                    b.HasIndex("UsuarioPartidaID");

                    b.ToTable("EstadosCarta");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoCartaID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurnoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoCartaID");

                    b.HasIndex("TurnoID");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ganador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.PerfilUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PartidasGanadas")
                        .HasColumnType("int");

                    b.Property<int>("PartidasJugadas")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.HasIndex(new[] { "Nombre" }, "PerfilesUsuario_Nombre_UQ")
                        .IsUnique();

                    b.ToTable("PerfilesUsuario");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Rankings");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Sobre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadCartas")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("NombreSobre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Sobres");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioPartidaID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioPartidaID");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "Usuarios_Email_UQ")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.UsuarioPartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aceptado")
                        .HasColumnType("bit");

                    b.Property<int>("CartasPerdidas")
                        .HasColumnType("int");

                    b.Property<int>("EstadoRegistro")
                        .HasColumnType("int");

                    b.Property<int>("PartidaID")
                        .HasColumnType("int");

                    b.Property<int>("PerfilUsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidaID");

                    b.HasIndex("PerfilUsuarioID");

                    b.ToTable("UsuariosPartida");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Amigo", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Usuario", "Usuario1")
                        .WithMany()
                        .HasForeignKey("Usuario1Id");

                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Usuario", "Usuario2")
                        .WithMany()
                        .HasForeignKey("Usuario2Id");

                    b.Navigation("Usuario1");

                    b.Navigation("Usuario2");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Billetera", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.CartaApertura", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.CartaSobre", "CartaSobre")
                        .WithMany()
                        .HasForeignKey("CartaSobreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.CompraSobre", "CompraSobre")
                        .WithMany()
                        .HasForeignKey("CompraSobreID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CartaSobre");

                    b.Navigation("CompraSobre");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.CartaSobre", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Carta", "Carta")
                        .WithMany()
                        .HasForeignKey("CartaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Sobre", "Sobre")
                        .WithMany()
                        .HasForeignKey("SobreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");

                    b.Navigation("Sobre");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.CompraSobre", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Sobre", "Sobre")
                        .WithMany()
                        .HasForeignKey("SobreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sobre");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.ConfiguracionUsuario", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.EstadoCarta", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.UsuarioPartida", "UsuarioPartida")
                        .WithMany()
                        .HasForeignKey("UsuarioPartidaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Inventario");

                    b.Navigation("UsuarioPartida");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Evento", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.EstadoCarta", "EstadoCarta")
                        .WithMany()
                        .HasForeignKey("EstadoCartaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EstadoCarta");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Inventario", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Carta", "Carta")
                        .WithMany()
                        .HasForeignKey("CartaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.PerfilUsuario", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Ranking", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.Turno", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.UsuarioPartida", "UsuarioPartida")
                        .WithMany()
                        .HasForeignKey("UsuarioPartidaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioPartida");
                });

            modelBuilder.Entity("Proyecto_Cartas.BD.Datos.Entidades.UsuarioPartida", b =>
                {
                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_Cartas.BD.Datos.Entidades.PerfilUsuario", "PerfilUsuario")
                        .WithMany()
                        .HasForeignKey("PerfilUsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("PerfilUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
